name: Android Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Run ktlint
        run: ./gradlew spotlessCheck

      - name: Run compileDebugKotlin
        run: ./gradlew compileDebugKotlin

      - name: Run Tests
        run: ./gradlew test

#      - name: Run Lint
#        run: ./gradlew lint

#      - name: Build Project (Debug)
#        run: ./gradlew assembleDebug
